name: 🐞 MEX 16 Bug Report
description: "This bug report is only for MEX 16."
title: "[Module]-[Sub module]-[Bug Description]"
body:
 - type: checkboxes
   attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
      - label: I have searched the existing issues
        required: true
 - type: dropdown
   id: ProductVersion
   attributes:
    label: What version you are using?
    options:
      - 1.0
      - 1.1
   validations:
     required: true
 - type: dropdown
   id: browser
   attributes:
    label: Issue occurs on specific browser?
    options:
      - All (Chrome, Edge, FireFox, Safari)
      - Chrome
      - Microsoft Edge
      - FireFox
      - Safari
   validations:
     required: true
 - type: dropdown
   id: raisedby
   attributes:
     label: Reported By
     description: Who should be contacted if the reported bug cannot replicate?
     options:
       - Alex Parker
       - Bonnie Tang
   validations:
     required: true
 - type: textarea
   id: repo
   attributes:
     label: Steps to reproduce the issue
     description: What another person has to do to see the bug
     placeholder: Tell us what you see!
     value: "1. \n2. \n3."
   validations:
     required: true
 - type: textarea
   id: ActualResult
   attributes:
     label: Actual Result
     description: A clear and concise description of what the bug is.
   validations:
     required: true
 - type: textarea
   attributes:
     label: Expected Behavior
     description: A clear and concise description of what you expected to happen.
   validations:
     required: false
 - type: textarea
   attributes:
     label: Additional Information / Logs / Videos / Screenshots 
     description:
     Links? References? Anything that will give us more context about the issue you are encountering!
     Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
   validations:
     required: false
