name: 🐞 MEX 16 Bug Report
description: File a bug report
title: ["Keep it fairly short but still more descriptive than e.g. WO is broken"]
labels: ["MEX 16 Bug Report"]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true
