name: 🐞 MEX 16 Bug Report
description: "This bug report is only for MEX 16."
title: "[Module]-[Sub module]-[Bug Description]"
labels: "MEX 16, Bug"
body:
 - type: checkboxes
   attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
      - label:  I have searched the existing issues
        required: false
 - type: dropdown
   id: wostatus
   attributes:
    label: WO Status?
    options:
      - Cancelled
      - Closed
      - Entered
      - In Progress
      - Investigation Required
      - Scheduled
      - Solution Provided
      - Started
      - Test Failed
      - Test Passed
    default: 2
   validations:
     required: true
 - type: dropdown
   id: severity
   attributes:
    label: Bug Severity?
    options:
      - Critical: Showstopper
      - Major: Key feature failed but have workaround
      - Moderate: Feature failed but no huge impact
      - Minor: Undesirable behavior but no major impact
      - Cosmetic: No impact on the functionality
    default: 1
   validations:
     required: true
 - type: dropdown
   id: reportedby
   attributes:
     label: Reported By
     description: Who should be contacted if the reported bug cannot replicate?
     options:
       - Bonnie
       - Buzz
       - Curtis
       - Ryan
       - Tyler
     default: 0
   validations:
     required: true
 - type: textarea
   id: repo
   attributes:
     label: Steps to reproduce the issue
     description: What another person has to do to see the bug
     placeholder: Tell us what you see!
     value:
        "\t Steps \t Expected Result \t Actual Result \n 1. \n 2. \n 3."
   validations:
     required: true
 - type: textarea
   id: ActualResult
   attributes:
     label: 👎 Actual Result
     description: A clear and concise description of what the bug is.
   validations:
     required: true
 - type: textarea
   attributes:
     label: 👍 Expected Behavior
     description: A clear and concise description of what you expected to happen.
   validations:
     required: false
 - type: textarea
   attributes:
     label: Additional Information / Logs / Videos / Screenshots
     description: |
      Links? References? Anything that will give us more context about the issue you are encountering!
      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
   validations:
     required: false
