name: 🐞 MEX 16 Bug Report
description: "Only file a bug which can replicate more than once!"
title: ""
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true
