name: 🐞 MEX 16 Bug Report
description: "Only file a bug which can replicate more than once!\n"
title: "[Module]-[Sub module]-[Bug Description]"
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true
   - type: dropdown
    id: versions
    attributes:
      label: What MEX 16 version are you using?
      multiple: true
      options:
        - 1.0
        - 1.1
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - All
        - Chrome 
        - Firefox
        - Microsoft Edge
        - Safari
