name: 🐞 MEX 16 Bug Report
description: "Only file a bug which can replicate more than once!\n"
title: "[Module]-[Sub module]-[Bug Description]"
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true
  -type: checkboxes
    attributes:
      label: Testing
      description: Testing
