name: 🐞 Bug Report
description: "This bug report is only for Bonnie Demo."
bug title: "[Module]-[Sub module]-[Bug Description]"
labels: "Bug"
body:
 - type: checkboxes
   attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
      - label:  I have searched the existing issues
        required: false
 - type: dropdown
   id: selecttype
   attributes:
    label: Select Type
    options:
      - "Content"
      - "Crash"
      - "Functional"
      - "Performance"
      - "Visual"
    default: 3
   validations:
     required: true
 - type: dropdown
   id: severity
   attributes:
    label: Bug Severity?
    options:
      - "Critical: Showstopper"
      - "Major: Key feature failed but have workaround"
      - "Moderate: Feature failed but no huge impact"
      - "Minor: Undesirable behavior but no major impact"
      - "Cosmetic: No impact on the functionality"
    default: 2
   validations:
     required: true
 - type: dropdown
   id: reportedby
   attributes:
     label: Reported By
     description: Who should be contacted if the reported bug cannot replicate?
     options:
       - Bonnie
     default: 0
   validations:
     required: true
 - type: textarea
   id: repo
   attributes:
     label: Steps to reproduce the issue
     description: What another person has to do to see the bug
     placeholder: Steps to reproduce the behavior.
     value: |
      1.
      2.
      3.
   validations:
     required: true
 - type: textarea
   id: ActualResult
   attributes:
     label: 👎 Actual Result
     description: A clear and concise description of what the bug is.
   validations:
     required: true
 - type: textarea
   attributes:
     label: 👍 Expected Behavior
     description: A clear and concise description of what you expected to happen.
   validations:
     required: false
 - type: textarea
   attributes:
     label: Additional Information / Logs / Videos / Screenshots
     description: |
      Links? References? Anything that will give us more context about the issue you are encountering!
      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
   validations:
     required: false
 - type: textarea
   attributes:
     label: Regression Test Case / Functionality Note
     description: |
      Regression Test Case Details / Function Changed Details
   validations:
     required: false
